### ISSUE TITLE
RFC: 2.0.0 Roadmap

### ISSUE THREAD

**Issue by davidyell** [UseMuffin/Webservice#51]
I wanted to quickly make some notes about things which I think could be worked on for the next major release of the plugin. This is a quick list and by no means exhaustive. Any suggestions are welcome

- [ ] CakePHP 3.5 support. Is it worth continuing work in the existing `3.4-test` branch?
- [ ] Adding pagination support
- [ ] Tidy up the api to remove confusing method names. Eg, `Endpoint::endpoint` and `Endpoint::endpoint()`
- [ ] Re-name some variables to better differentiate between strings and instances
- [ ] Bump code sniffer version and fix any warnings
- [ ] Add phpstan, with a script for basic support such as level 2
- [ ] Bump phpunit to 7.x and update the test suite
- [ ] Fix the FixtureListener in the `phpunit.xml` file as PHPUnit 7.x doesn't have the `BaseListener` class
- [ ] Where appropriate refactor mixed mode methods, such as `Endpoint::endpoint()` and `Endpoint::alias()` to getters and setters
- [ ] Implement the new `setAlias()` and `getAlias()` methods which are now part of the core `RepositoryInterface` into the Endpoints
- [ ] Replace the useless `{@inheritDoc}` doc blocks with actual doc blocks
- [ ] Upgrade to usage of `setConfig()` and `getConfig()`
- [ ] Move the `AbstractDriver` class into the `Driver` folder and update it's namespace
- [ ] [If no results are found, the returned total should be zero](https://github.com/UseMuffin/Webservice/compare/master...davidyell:develop#diff-4528a13e17ddcea8ae7919377e58843bL431)

**Comment by ADmad** [comment]
> CakePHP 3.5 support. Is it worth continuing work in the existing 3.4-test branch?
I am fine with bumping CakePHP version to 3.5. Let's start by doing that and updating the deprecated methods/properties. Please try and make small PRs addressing one point at a time.

> Add phpstan, with a script for basic support such as level 2
Current master already passes phpstan checks at level 2.
https://github.com/UseMuffin/Webservice/blob/master/.travis.yml#L39

> Bump phpunit to 7.x and update the test suite
Unless CakePHP core is updated to support phpunit 7 this can't be done.

**Comment by ADmad** [comment]
> Move the AbstractDriver class into the Driver folder and update it's namespace

What benefit does that achieve? I dislike changes just for the sake of it.

> If no results are found, the returned total should be zero

Doesn't #44 already take care of this?

**Comment by davidyell** [comment]
Any thoughts @Marlinc ? Would you see #23 as something for the 2.x release?

**Comment by davidyell** [comment]
@ADmad Are you happy for me to target `master` or would you prefer a new release branch?

**Comment by ADmad** [comment]
Just target master, I can change target later if needed.

**Comment by davidyell** [comment]
@ceeram Would you like to contribute a few tests in #49 so we can include your changes in the release?

**Comment by davidyell** [comment]
- [ ] Refactor `Schema::options()`
- [ ] Refactor `Schema::columnType()`

**Comment by ADmad** [comment]
@davidyell Okay, I think we can tag 2.0 once readme is updated. Should we do a beta / RC first before 2.0 stable?

**Comment by ADmad** [comment]
I noticed an unfinished branch for form context class for resource https://github.com/UseMuffin/Webservice/tree/form-context. Would be nice if that could be finished and included in 2.0.

**Comment by davidyell** [comment]
Yes, I think we could tag an RC release.

I would think that actually the form context and associations branches would be post 2.0 features, as with the pagination.

I will update the readme this morning.
